version: '2'

services:
    web:
        build:
            context: ./nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www
        networks:
            - code-network
    php:
        build:
            context: ./php
        volumes:
            - ./src:/var/www
        networks:
            - code-network

networks:
    code-network:
        driver: bridge